# Generated by Django 3.2.4 on 2021-10-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
