# Generated by Django 3.2.4 on 2021-10-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_student_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.ManyToManyField(to='home.Department'),
        ),
    ]
