# Generated by Django 3.2.6 on 2021-10-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20211004_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='s_no',
            field=models.IntegerField(default=0),
        ),
    ]
